### ISSUE TITLE
cursor problems from CodeMirror linewrap

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#124]
- win10 + chrome
- hexo-admin @github version

---

when the line wrap auto, the cursor will like this:
![qq 20170223223352](https://cloud.githubusercontent.com/assets/6964173/23263205/797d1d64-fa18-11e6-981f-31e5f9c646f9.png)

**Comment by PirtleShell** [comment]
I'm sorry, I'm not able to reproduce this on chrome or firefox. It's possible my CSS changes to accommodate firefox caused this, but wrapped lines correctly display the cursor for me.

Does this happen for all long lines you have?

Although the ends of long lines are hard for me to select...I can only choose a location on the first line of a wrapped area.

It looks like the problem is because CodeMirror is flexing, there's discrepancy between how long the js thinks the lines are vs how long they actually are. There appear to be [many browser problems that cause CodeMirror to not display properly in flexbox](https://github.com/codemirror/CodeMirror/issues?utf8=%E2%9C%93&q=is%3Aissue%20flexbox%20). I'll work on a solution to the un-selectable lines and see if it fixes your problem.

**Comment by PirtleShell** [comment]
I also updated codemirror.
Please see if that fixes the cursor trouble you were having.

**Comment by xbotao** [comment]
There is a `build error` for me. #126
