### ISSUE TITLE
deploy command with no message text throws ENOENT

### ISSUE THREAD

**Issue by xxccode** [jaredly/hexo-admin#143]
when I deploy the blog in "Deploy" Tabs page via the Deploy button,  I got an error message: Error: Config value "admin.deployCommand" not found

**Comment by fadehelix** [comment]
The solution I found is to [edit your deploy configuration](https://hexo.io/docs/deployment.html), then add to _config.yml these lines:
```
# Admin
admin:
  deployCommand: hexo
```  
Then you have to type `deploy` in the "Deploy/commit message" field in admin panel.

**Comment by SeanHsu** [comment]
got an Error message: Config value "admin.deployCommand" not found.

**Comment by Haocen** [comment]
Honestly I think this should be executing `hexo deploy` by default if value not set.

**Comment by superman66** [comment]
@fadehelix  thanks, it works.

**Comment by pirtleshell** [comment]
oh wait, i am misunderstanding... the problem here is that it should be okay with not entering anything in the message box and just run the deploy command if `hexo deploy` is the command defined in your config. i apologize for not understanding. i agree that's pretty silly and will reopen the issue.

**Comment by pirtleshell** [comment]
nope, i'm misunderstanding everything. 🤦‍♂️ hahaha, sorry for all this mumbojumbo.

i see now what you are saying. yes. just enter `hexo deploy` as your deployment command and you will not need to type anything in the message box.... :fire:
