### ISSUE TITLE
Filename of new post

### ISSUE THREAD

**Issue by KarelWintersky** [jaredly/hexo-admin#145]
Filename of new post must be started from post's date.. and must be changed when post date changed.

Now:
```
Downloaded-from-RPOD-ru.md 
```

must be:
```
[2016-08-28] Downloaded-from-RPOD-ru.md 
```
or (without space)
```
[2016-08-28]Downloaded-from-RPOD-ru.md 
```

Also, datetime format must be tuneable in `_config.yml` (inside theme config or global config)

So, sorting post will be more useful

**Comment by pirtleshell** [comment]
hello,

AFAIK there are no hard rules on the names of posts. it's been a while since i've looked at all this, but i'm pretty confident that hexo-admin will use whatever naming convention has been setup in hexo's config.

as for changing names when the date changes, we make no assumptions about the naming convention you are using in your posts, and thus do not alter any post names. if you'd like to rename a post's filename, you can click the filename that appears above the editor and it becomes editable:

![](https://cloud.githubusercontent.com/assets/14897503/22187327/02709eb0-e0ca-11e6-824f-cd2b072c673d.png)
