### ISSUE TITLE
Image Pasting cannot work on Ubuntu

### ISSUE THREAD

**Issue by xdkxlk** [jaredly/hexo-admin#170]
System: Ubuntu 16.04.5 LTS x86_64
Browser: Google Chrome 67.0.3396.99
When I paste images to the browser, it just paste the path, not the image
![image](https://user-images.githubusercontent.com/10397306/43987273-ee10448a-9d50-11e8-8a1e-86974de4367b.png)

**Comment by pirtleshell** [comment]
my guess is that this has to do with what Ubuntu actually puts in your clipboard when you copy an image. i've run hexo-admin on a linux box before and it didn't have a problem uploading pasted images. it looks like you may be trying to copy an actual file from your computer and pasting it, rather than copying image data.

can you confirm it still does not work when copying an image directly from a website and pasting it into your editor?

**Comment by xdkxlk** [comment]
Oh, it can work if copy image from website
