### ISSUE TITLE
how to set up hexo-admin in gh-pages

### ISSUE THREAD

**Issue by whelamc** [jaredly/hexo-admin#41]

**Comment by whelamc** [comment]
issue name

**Comment by jaredly** [comment]
The way I do it:
```
cd my-hexo-blog
git clone git@...my-repo.git pages --branch=gh-pages
hexo gen
rsync -r public/ pages
cd pages && git commit -am "update" && git push
```

**Comment by whelamc** [comment]
maybe i write the wrong issue name , i want use the hexo-admin for my hexo page and which is bulit in gh-pages branch in other repo not the xxx.github.io , how can i do that?

**Comment by jaredly** [comment]
do you want hexo-admin to be *usable from gh-pages*? As in "I go to some-site.com/admin (hosted by gh-pages) and it works?" because that's not possible - github pages is a **static** host, and can't have dynamic things like hexo-admin.

If you want to know how to publish hexo to gh-pages, see my script, or I'm sure the hexo docs have great instructions.
