### ISSUE TITLE
Can't deploy hexo-admin

### ISSUE THREAD

**Issue by juno249** [jaredly/hexo-admin#49]
Recently, i wanna to deploy my Blog with this plugin to Heroku.
But, i was not found when i access to `http://<domain-name>/admin`
Tell me why i can't deploy it?

**Comment by jaredly** [comment]
hmmm that ought to work. what's your heroku `Procfile`?

**Comment by juno249** [comment]
when i deployed on localhost `0.0.0.0:4000/admin`. Everything is ok. But on Heroku, for example: `subdomain-heroku.herokuapp.com/admin`. It's not work.

**Comment by jaredly** [comment]
and you're running locally w/ the Procfile? One possibliity is you're just using static files on heroku.

**Comment by huguiqi** [comment]
Recently, i wanna to deploy my Blog with this plugin to Heroku too.tell me why?thanks...

**Comment by kaichi** [comment]
no documentation on how to configure deploy? I am using hexo-deployer-git - what do?

**Comment by jaredly** [comment]
@kaichi @huguiqi there are two ways to deploy hexo: static pages or as a running server.
- static pages: you run `hexo generate` locally, and then the resulting HTML & CSS files are hosted somewhere
- running server: the host (like heroku) runs `hexo server`, and pages are generated dynamically

I personally recommend static pages, because it is much cheaper and more efficient. However, when using static pages, `hexo-admin` is not accessible from your website, but is only accessible locally.
If you are using a running server for your website, then `hexo-admin` will be available at e.g. `example.com/admin`, and you will be able to edit blog posts from the running server without having to redeploy.

Which scenario are you asking about?

**Comment by jaredly** [comment]
to deploy dynamically to heroku, I imagine you would just need a `Procfile` like
```
web: hexo server
```
and then deploy heroku normally, the way explained in https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by jjalan** [comment]
I solved it as follows:

1. Create index.js file in root directory of your project that contains the following:

~~~
var exec = require('child_process').exec;

var port = process.env.PORT || 4000;
var hexoServerProcess = exec("hexo server -p " + port);

hexoServerProcess.stdout.on('data', function(data) {
    console.log(data.toString()); 
});
~~~

2. Add following line in package.json
~~~
"scripts": {
    "start": "node index.js"
  }
~~~

3. Now deploy using (do not use hexo heroku plugin as it only deploy static pages)
~~~
git push heroku master
~~~
This assumes that you have added heroku as remote pointing to your heroku git.

Working link to my admin:
https://trysquad-blog.herokuapp.com/blog/admin

Complete details (end to end):
https://trysquad-blog.herokuapp.com/blog/2016/12/31/Easiest-way-to-start-hexo-blog-for-your-website/
